[2022-04-01 19:38:53,483] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-03-01T00:00:00+00:00 [None]>
[2022-04-01 19:38:53,500] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-03-01T00:00:00+00:00 [None]>
[2022-04-01 19:38:53,500] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 19:38:53,500] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-04-01 19:38:53,500] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 19:38:53,514] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2022-03-01T00:00:00+00:00
[2022-04-01 19:38:53,520] {standard_task_runner.py:52} INFO - Started process 26610 to run task
[2022-04-01 19:38:53,527] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'upload_file_to_s3', '2022-03-01T00:00:00+00:00', '--job-id', '72', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpd26h0w1f', '--error-file', '/tmp/tmp_i3rwra9']
[2022-04-01 19:38:53,529] {standard_task_runner.py:77} INFO - Job 72: Subtask upload_file_to_s3
[2022-04-01 19:38:53,569] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2022-03-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 19:38:53,612] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=upload_file_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-01T00:00:00+00:00
[2022-04-01 19:38:53,614] {base_aws.py:396} INFO - Airflow Connection: aws_conn_id=s3_con
[2022-04-01 19:38:53,621] {base_aws.py:419} WARNING - Unable to use Airflow Connection for credentials.
[2022-04-01 19:38:53,622] {base_aws.py:420} INFO - Fallback on boto3 credential strategy
[2022-04-01 19:38:53,622] {base_aws.py:425} INFO - Creating session using boto3 credential strategy region_name=us-west-2
[2022-04-01 19:38:53,641] {credentials.py:1100} INFO - Found credentials in environment variables.
[2022-04-01 19:39:02,193] {python.py:151} INFO - Done. Returned value was: None
[2022-04-01 19:39:02,203] {taskinstance.py:1218} INFO - Marking task as SUCCESS. dag_id=divvybikes_elt_pipeline, task_id=upload_file_to_s3, execution_date=20220301T000000, start_date=20220401T193853, end_date=20220401T193902
[2022-04-01 19:39:02,237] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-04-01 19:39:02,254] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
