[2022-04-01 20:53:57,561] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2020-12-01T00:00:00+00:00 [queued]>
[2022-04-01 20:53:57,581] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2020-12-01T00:00:00+00:00 [queued]>
[2022-04-01 20:53:57,582] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:53:57,582] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-04-01 20:53:57,582] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:53:57,589] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2020-12-01T00:00:00+00:00
[2022-04-01 20:53:57,592] {standard_task_runner.py:52} INFO - Started process 2330 to run task
[2022-04-01 20:53:57,595] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'upload_file_to_s3', '2020-12-01T00:00:00+00:00', '--job-id', '132', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpgi1wfd2s', '--error-file', '/tmp/tmpe7itrykm']
[2022-04-01 20:53:57,596] {standard_task_runner.py:77} INFO - Job 132: Subtask upload_file_to_s3
[2022-04-01 20:53:57,627] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2020-12-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 20:53:57,665] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=upload_file_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2020-12-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2020-12-01T00:00:00+00:00
[2022-04-01 20:53:57,667] {base_aws.py:396} INFO - Airflow Connection: aws_conn_id=s3_con
[2022-04-01 20:53:57,672] {base_aws.py:419} WARNING - Unable to use Airflow Connection for credentials.
[2022-04-01 20:53:57,672] {base_aws.py:420} INFO - Fallback on boto3 credential strategy
[2022-04-01 20:53:57,672] {base_aws.py:425} INFO - Creating session using boto3 credential strategy region_name=us-west-2
[2022-04-01 20:53:57,686] {credentials.py:1100} INFO - Found credentials in environment variables.
[2022-04-01 20:54:09,201] {python.py:151} INFO - Done. Returned value was: None
[2022-04-01 20:54:09,285] {taskinstance.py:1218} INFO - Marking task as SUCCESS. dag_id=divvybikes_elt_pipeline, task_id=upload_file_to_s3, execution_date=20201201T000000, start_date=20220401T205357, end_date=20220401T205409
[2022-04-01 20:54:09,340] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-04-01 20:54:09,363] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
