[2022-04-01 20:30:31,649] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2020-04-01T00:00:00+00:00 [queued]>
[2022-04-01 20:30:31,661] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2020-04-01T00:00:00+00:00 [queued]>
[2022-04-01 20:30:31,661] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:30:31,661] {taskinstance.py:1095} INFO - Starting attempt 2 of 3
[2022-04-01 20:30:31,661] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:30:31,667] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2020-04-01T00:00:00+00:00
[2022-04-01 20:30:31,671] {standard_task_runner.py:52} INFO - Started process 32107 to run task
[2022-04-01 20:30:31,673] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'upload_file_to_s3', '2020-04-01T00:00:00+00:00', '--job-id', '93', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp515po8q2', '--error-file', '/tmp/tmpntcpw4cf']
[2022-04-01 20:30:31,675] {standard_task_runner.py:77} INFO - Job 93: Subtask upload_file_to_s3
[2022-04-01 20:30:31,705] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2020-04-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 20:30:31,744] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=upload_file_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2020-04-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2020-04-01T00:00:00+00:00
[2022-04-01 20:30:31,745] {base_aws.py:396} INFO - Airflow Connection: aws_conn_id=s3_con
[2022-04-01 20:30:31,751] {base_aws.py:419} WARNING - Unable to use Airflow Connection for credentials.
[2022-04-01 20:30:31,751] {base_aws.py:420} INFO - Fallback on boto3 credential strategy
[2022-04-01 20:30:31,751] {base_aws.py:425} INFO - Creating session using boto3 credential strategy region_name=us-west-2
[2022-04-01 20:30:31,765] {credentials.py:1100} INFO - Found credentials in environment variables.
[2022-04-01 20:30:37,983] {python.py:151} INFO - Done. Returned value was: None
[2022-04-01 20:30:37,991] {taskinstance.py:1218} INFO - Marking task as SUCCESS. dag_id=divvybikes_elt_pipeline, task_id=upload_file_to_s3, execution_date=20200401T000000, start_date=20220401T203031, end_date=20220401T203037
[2022-04-01 20:30:38,014] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-04-01 20:30:38,032] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
