[2022-04-01 21:12:35,107] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2021-10-01T00:00:00+00:00 [queued]>
[2022-04-01 21:12:35,127] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2021-10-01T00:00:00+00:00 [queued]>
[2022-04-01 21:12:35,127] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 21:12:35,127] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2022-04-01 21:12:35,127] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 21:12:35,134] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2021-10-01T00:00:00+00:00
[2022-04-01 21:12:35,137] {standard_task_runner.py:52} INFO - Started process 4662 to run task
[2022-04-01 21:12:35,141] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'upload_file_to_s3', '2021-10-01T00:00:00+00:00', '--job-id', '192', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpev2d127y', '--error-file', '/tmp/tmpn7ris1ly']
[2022-04-01 21:12:35,143] {standard_task_runner.py:77} INFO - Job 192: Subtask upload_file_to_s3
[2022-04-01 21:12:35,176] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.upload_file_to_s3 2021-10-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 21:12:35,218] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=upload_file_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2021-10-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=backfill__2021-10-01T00:00:00+00:00
[2022-04-01 21:12:35,220] {base_aws.py:396} INFO - Airflow Connection: aws_conn_id=s3_con
[2022-04-01 21:12:35,227] {base_aws.py:419} WARNING - Unable to use Airflow Connection for credentials.
[2022-04-01 21:12:35,227] {base_aws.py:420} INFO - Fallback on boto3 credential strategy
[2022-04-01 21:12:35,227] {base_aws.py:425} INFO - Creating session using boto3 credential strategy region_name=us-west-2
[2022-04-01 21:12:35,241] {credentials.py:1100} INFO - Found credentials in environment variables.
[2022-04-01 21:13:35,406] {python.py:151} INFO - Done. Returned value was: None
[2022-04-01 21:13:35,417] {taskinstance.py:1218} INFO - Marking task as SUCCESS. dag_id=divvybikes_elt_pipeline, task_id=upload_file_to_s3, execution_date=20211001T000000, start_date=20220401T211235, end_date=20220401T211335
[2022-04-01 21:13:35,455] {local_task_job.py:151} INFO - Task exited with return code 0
[2022-04-01 21:13:35,473] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
