[2022-04-01 20:04:52,052] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-01 20:04:52,064] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-01 20:04:52,064] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:04:52,064] {taskinstance.py:1095} INFO - Starting attempt 6 of 7
[2022-04-01 20:04:52,064] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:04:52,071] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): download_dataset> on 2022-03-01T00:00:00+00:00
[2022-04-01 20:04:52,076] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'download_dataset', '2022-03-01T00:00:00+00:00', '--job-id', '78', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpe625t_sw', '--error-file', '/tmp/tmp_qr5_53j']
[2022-04-01 20:04:52,074] {standard_task_runner.py:52} INFO - Started process 29353 to run task
[2022-04-01 20:04:52,077] {standard_task_runner.py:77} INFO - Job 78: Subtask download_dataset
[2022-04-01 20:04:52,107] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 20:04:52,133] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1245, in _prepare_and_execute_task_with_callbacks
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1754, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 997, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 1010, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 1047, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/sandbox.py", line 460, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/sandbox.py", line 360, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'strfttime'
[2022-04-01 20:04:52,135] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=download_dataset, execution_date=20220301T000000, start_date=20220401T200452, end_date=20220401T200452
[2022-04-01 20:04:52,170] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-01 20:04:52,189] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
