[2022-04-01 20:05:55,774] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-01 20:05:55,797] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-01 20:05:55,798] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:05:55,798] {taskinstance.py:1095} INFO - Starting attempt 7 of 8
[2022-04-01 20:05:55,798] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:05:55,808] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): download_dataset> on 2022-03-01T00:00:00+00:00
[2022-04-01 20:05:55,812] {standard_task_runner.py:52} INFO - Started process 29474 to run task
[2022-04-01 20:05:55,815] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'download_dataset', '2022-03-01T00:00:00+00:00', '--job-id', '79', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmp9scuydgx', '--error-file', '/tmp/tmpypdz4lw5']
[2022-04-01 20:05:55,816] {standard_task_runner.py:77} INFO - Job 79: Subtask download_dataset
[2022-04-01 20:05:55,847] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 20:05:55,901] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=download_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-01T00:00:00+00:00
[2022-04-01 20:05:55,903] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-04-01 20:05:55,904] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'curl -sSL https://divvy-tripdata.s3.amazonaws.com/202203-divvy-tripdata.zip > /opt/***/dags/datasets//opt/***/dags/datasets202203-divvy-tripdata.zip']
[2022-04-01 20:05:55,912] {subprocess.py:74} INFO - Output:
[2022-04-01 20:05:55,913] {subprocess.py:78} INFO - bash: /opt/***/dags/datasets//opt/***/dags/datasets202203-divvy-tripdata.zip: No such file or directory
[2022-04-01 20:05:55,914] {subprocess.py:82} INFO - Command exited with return code 1
[2022-04-01 20:05:55,924] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-01 20:05:55,925] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=download_dataset, execution_date=20220301T000000, start_date=20220401T200555, end_date=20220401T200555
[2022-04-01 20:05:55,948] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-01 20:05:55,983] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
