[2022-04-01 20:10:06,971] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-01 20:10:06,988] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [queued]>
[2022-04-01 20:10:06,988] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:10:06,988] {taskinstance.py:1095} INFO - Starting attempt 8 of 9
[2022-04-01 20:10:06,988] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-04-01 20:10:06,995] {taskinstance.py:1114} INFO - Executing <Task(BashOperator): download_dataset> on 2022-03-01T00:00:00+00:00
[2022-04-01 20:10:07,000] {standard_task_runner.py:52} INFO - Started process 29908 to run task
[2022-04-01 20:10:07,002] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'divvybikes_elt_pipeline', 'download_dataset', '2022-03-01T00:00:00+00:00', '--job-id', '80', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpsifasrhn', '--error-file', '/tmp/tmph_mjnuv5']
[2022-04-01 20:10:07,003] {standard_task_runner.py:77} INFO - Job 80: Subtask download_dataset
[2022-04-01 20:10:07,031] {logging_mixin.py:109} INFO - Running <TaskInstance: divvybikes_elt_pipeline.download_dataset 2022-03-01T00:00:00+00:00 [running]> on host b399ffa6f3b6
[2022-04-01 20:10:07,067] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=divvybikes_elt_pipeline
AIRFLOW_CTX_TASK_ID=download_dataset
AIRFLOW_CTX_EXECUTION_DATE=2022-03-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-01T00:00:00+00:00
[2022-04-01 20:10:07,068] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-04-01 20:10:07,069] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'curl -sSL https://divvy-tripdata.s3.amazonaws.com/202203-divvy-tripdata.zip > /opt/***/dags/datasets//opt/***/dags/datasets202203-divvy-tripdata.zip']
[2022-04-01 20:10:07,076] {subprocess.py:74} INFO - Output:
[2022-04-01 20:10:07,078] {subprocess.py:78} INFO - bash: /opt/***/dags/datasets//opt/***/dags/datasets202203-divvy-tripdata.zip: No such file or directory
[2022-04-01 20:10:07,078] {subprocess.py:82} INFO - Command exited with return code 1
[2022-04-01 20:10:07,087] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-04-01 20:10:07,088] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=divvybikes_elt_pipeline, task_id=download_dataset, execution_date=20220301T000000, start_date=20220401T201006, end_date=20220401T201007
[2022-04-01 20:10:07,135] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-04-01 20:10:07,159] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
