[2022-03-29 00:15:44,815] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: extract_load_to_s3.stream_files_to_memory 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-29 00:15:44,827] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: extract_load_to_s3.stream_files_to_memory 2022-03-20T00:00:00+00:00 [queued]>
[2022-03-29 00:15:44,827] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 00:15:44,828] {taskinstance.py:1095} INFO - Starting attempt 11 of 12
[2022-03-29 00:15:44,828] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2022-03-29 00:15:44,835] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): stream_files_to_memory> on 2022-03-20T00:00:00+00:00
[2022-03-29 00:15:44,838] {standard_task_runner.py:52} INFO - Started process 2853 to run task
[2022-03-29 00:15:44,840] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'extract_load_to_s3', 'stream_files_to_memory', '2022-03-20T00:00:00+00:00', '--job-id', '18', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/extract_load.py', '--cfg-path', '/tmp/tmpan091hk8', '--error-file', '/tmp/tmpy2asrwxm']
[2022-03-29 00:15:44,842] {standard_task_runner.py:77} INFO - Job 18: Subtask stream_files_to_memory
[2022-03-29 00:15:44,873] {logging_mixin.py:109} INFO - Running <TaskInstance: extract_load_to_s3.stream_files_to_memory 2022-03-20T00:00:00+00:00 [running]> on host 06cd4100c9db
[2022-03-29 00:15:44,908] {taskinstance.py:1253} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_load_to_s3
AIRFLOW_CTX_TASK_ID=stream_files_to_memory
AIRFLOW_CTX_EXECUTION_DATE=2022-03-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-20T00:00:00+00:00
[2022-03-29 00:15:48,278] {python.py:151} INFO - Done. Returned value was: ('202004-divvy-tripdata.csv', <zipfile.ZipExtFile [closed]>)
[2022-03-29 00:15:48,280] {xcom.py:229} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2022-03-29 00:15:48,280] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1904, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 79, in set
    value = XCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/xcom.py", line 226, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ZipExtFile' is not JSON serializable
[2022-03-29 00:15:48,282] {taskinstance.py:1512} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_load_to_s3, task_id=stream_files_to_memory, execution_date=20220320T000000, start_date=20220329T001544, end_date=20220329T001548
[2022-03-29 00:15:48,426] {local_task_job.py:151} INFO - Task exited with return code 1
[2022-03-29 00:15:48,453] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
